### ISSUE TITLE
[Feature Request] list of current congressional districts per state

### ISSUE THREAD

**Issue by AlJohri** [unitedstates/python-us#17]

**Comment by jcarbaugh** [comment]
@AlJohri district information sounds incredibly useful, but I think it's outside the scope of what python-us is trying to accomplish. Most of the data in python-us changes so infrequently that it's virtually static. District data changes often enough that APIs or other data sources are a better choice.

If you know of an open endpoint that provides that information, it could make sense to include that on the state so that people that do need the information have a programmatic way of accessing the data without having to look up another resource or downloading another package.
